#!/usr/bin/env python3
# TODO

#---------------------------------
# Prints on console sentiment score (and associated color code) for each tweet from a Twitter account. 
#----------------------------------

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @user")
        
    twitterAccount = helpers.get_user_timeline(sys.argv[1], 100)             # get a list of tweets (as strings)
    
    if twitterAccount == None:                                               # test if screen_name exists/ is not private/ no error
        return sys.exit()

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    for tweet in twitterAccount:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(score, "green"), colored(tweet, "green"))
        elif score < 0.0:
            print(colored(score, "red"), colored(tweet, "red"))
        else:
            print(colored(score, "yellow"), colored(tweet, "yellow"))

if __name__ == "__main__":
    main()
